---
title: "Complaints 2020 nta analysis"
output: pdf_document
---

```{r}
library(tidyverse)
library(Matrix)

rm(list = ls())
gc()
```


## Explorative analysis

```{r}
# read the data
com_20_nta = read.csv("../../data/core_datasets/complaints/complaints_2020_nta.csv", stringsAsFactors = T)
```

```{r}
str(com_20_nta)

# convert to factor
com_20_nta$JURISDICTION_CODE = as.factor(com_20_nta$JURISDICTION_CODE)
com_20_nta$KY_CD = as.factor(com_20_nta$KY_CD)
com_20_nta$MONTH = as.factor(com_20_nta$MONTH)
```


Group by all variables and create a new variable for the count.
```{r}
grouped_com <- com_20_nta %>%
  group_by(across(everything())) %>%
  summarise(count = n())

dim(grouped_com)
```

```{r}
table(grouped_com$count)
```

Make model matrix
```{r}
# add interactions
X = sparse.model.matrix(count ~ -1 + . + NTA2020:MONTH + NTA2020:KY_CD, data = grouped_com)

dim(X)
```

Try linear regression model.
```{r}
W = t(X) %*% X

beta = solve(W) %*% t(X) %*% as.matrix(grouped_com$count)
```







